# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_生成用户表'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name='验证邮箱状态'),
        ),
    ]
